### ISSUE TITLE
Error during renewal process

### ISSUE THREAD

**Issue by openmatl** [plesk/letsencrypt-plesk#90]
Hello,

I am using Plesk 12.5.30 Update #24 on CentOS Linux 7.2.1511 (Core)‬.
Installed version of Let's Encrypt (Plesk plugin) is 1.5.
During the renewal process I am getting the following error and therefore no ne certs.

Any suggestions on how to solve the issue?

Best regards
matl

`Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: Traceback (most recent call last):
File &quot;/usr/local/psa/var/modules/letsencrypt/venv/bin/letsencrypt&quot;, line 11, in &lt;module&gt;
sys.exit(main())
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages/letsencrypt/cli.py&quot;, line 1950, in main
plugins = plugins_disco.PluginsRegistry.find_all()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 168, in find_all
plugin_ep = PluginEntryPoint(entry_point)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 31, in __init__
self.plugin_cls = entry_point.load()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2201, in load
self.require(*args, **kwargs)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2218, in require
items = working_set.resolve(reqs, env, installer)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 835, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.1 (/usr/local/psa/var/modules/letsencrypt/venv.COlED/lib/python2.7/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))`

**Comment by Rewur** [comment]
Same issue here
OS: ‪Debian 7.9‬
Plesk 12.5.30 Update Nr. 27

`Fehler: Fehler bei der Installation des SSL-Zertifikats von Let's Encrypt: Failed letsencrypt execution: Traceback (most recent call last):
File &quot;/opt/psa/var/modules/letsencrypt/venv/bin/letsencrypt&quot;, line 11, in &lt;module&gt;
sys.exit(main())
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Vnb5L/local/lib/python2.7/site-packages/letsencrypt/cli.py&quot;, line 1950, in main
plugins = plugins_disco.PluginsRegistry.find_all()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Vnb5L/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 168, in find_all
plugin_ep = PluginEntryPoint(entry_point)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Vnb5L/local/lib/python2.7/site-packages/letsencrypt/plugins/disco.py&quot;, line 31, in __init__
self.plugin_cls = entry_point.load()
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Vnb5L/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2201, in load
self.require(*args, **kwargs)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Vnb5L/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 2218, in require
items = working_set.resolve(reqs, env, installer)
File &quot;/usr/local/psa/var/modules/letsencrypt/venv.Vnb5L/local/lib/python2.7/site-packages/pkg_resources/__init__.py&quot;, line 835, in resolve
raise VersionConflict(dist, req).with_context(dependent_req)
ContextualVersionConflict: (cryptography 1.1 (/opt/psa/var/modules/letsencrypt/venv.Vnb5L/lib/python2.7/site-packages), Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))`

**Comment by openmatl** [comment]
Any ideas on how to update the certificates manually via terminal. "letsencrypt" is not available in terminal.

**Comment by xgin** [comment]
The dependency issue with "Requirement.parse('cryptography&gt;=1.3'), set(['PyOpenSSL']))" has already been fixed in our repositories.
Just in case you (or your hosting provider) use a mirror, it might have been unsynchronized.
As far as I know our repository has been migrated into another data center.
Try adding in /etc/hosts `195.214.233.107 autoinstall.plesk.com`

**Comment by openmatl** [comment]
Hello,
I installed updates yesterday. There was a update plesk-letsencrypt:
`plesk-letsencrypt-pre.x86_64 0:1.0.0-centos7.16032214`

Also added your line to /etc/hosts but no updates so far.
The error still exists anyway.

**Comment by xgin** [comment]
@openmatl yep, because `yum update` is not enough
Run `plesk bin extension --exec letsencrypt post-install.php`

**Comment by openmatl** [comment]
Thanks a lot. It is working again on both of my servers. :+1: 

```
plesk bin extension --exec letsencrypt post-install.php

Bootstrapping dependencies for centos 7 x86_64...
Paket plesk-letsencrypt-pre-1.0.0-centos7.16032214.x86_64 ist bereits in der neuesten Version installiert.
Creating virtual environment...
Updating letsencrypt and virtual environment dependencies...
  Could not find .egg-info directory in install record for setuptools from https://pypi.python.org/packages/source/s/setuptools/setuptools-20.6.6.tar.gz#md5=77d29ce21958f030b47be9669c87027c in /usr/local/psa/var/modules/letsencrypt/venv.ZnoKC/lib/python2.7/site-packages
  Could not find .egg-info directory in install record for pip from https://pypi.python.org/packages/source/p/pip/pip-8.1.1.tar.gz#md5=6b86f11841e89c8241d689956ba99ed7 in /usr/local/psa/var/modules/letsencrypt/venv.ZnoKC/lib/python2.7/site-packages
Switch venv to the installed one...
Done

```
